-- TODO: this query is used to create the package1_all table
--  this query needs to be made dynamic based on the columns in the view vw_HIVProject1_1



select  * from  ( 
				select s.id, a.SiteId, s.Name, CatchmentId, ReportId, ChampsId, 
                FieldName, FieldValue
			from vw_HIVProject1_1 (nolock) a join Site s on a.SiteId = s.SiteId
) AS SourceTable pivot (max(FieldValue) for FieldName in 
(  
report_ver_nmb,
report_note_dt,
report_note_time,
report_child_firstname,
report_child_surname,
report_sex,
idnf_dobclass,
report_dob,
report_age_class,
idnf_dodclass,
report_death_dt,
report_death_time,
report_death_location,
report_dthloc_other,
report_dthloc_code,
report_dthloc_facility_other,
report_buried,
report_caretaker_firstname,
report_caretaker_surname,
report_care_religion,
report_carerelig_other,
report_notes,
calc_age_years,
report_eligibility,
report_decision,
deceased_residence,
delay_reason,
report_not_elig,
dnmf_exclindic,
report_explain_reason,
report_decision_dt,
elig_conduct,
elig_not_able,
elig_dt,
elig_time,
elig_verbal_request,
elig_verbal_request_why,
elig_verbal_granted,
esfv4_verbal_granted_why,
esfv4_confirmageclass,
esfv4_age_class,
elig_dob_confirm,
esfv4_dobclass,
elig_dob,
elig_dod_confirm,
esfv4_dobclass_2,
elig_dod,
elig_confirm_time,
elig_dth_time,
esf_locdeathconfirm,
elig_dth_loc,
elig_dth_loc_oth,
elig_dth_address,
elig_facility_visit,
elig_facility_code,
elig_facility_other,
elig_narrative,
elig_child_dss,
elig_legal,
esf_bodyavail,
elig_mits,
elig_enroll,
elig_descriptive_2,
elig_mits_consent_dt,
elig_mits_request,
elig_mits_request_no,
elig_mits_consent,
elig_mits_refuse,
elig_mits_refother,
elig_mits_refreason,
champs_id,
hiv_prior,
adu_hiv,
mits_type,
elig_staff_name,
elig_staff_phone,
elig_staff_notes,
initial_death_notification_complete,
death_notification_management_complete,
eligibility_screening_form_complete,
consent_tracking_complete
)) pvt 
GO