#!/usr/bin/env python3
"""
Script to load HIV 6.1 data from CSV into SQL Server.

Usage:
    python load_hiv_6_1_data.py <path_to_csv>
"""

import os
import sys
import pandas as pd
from datetime import datetime
from pathlib import Path
from sqlalchemy import text

# Import project configuration
sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from config.config import CONN

# Configuration
SCHEMA = "hiv"
TABLE_NAME = "HIVProject6_1ICD"
CHUNK_SIZE = 10000  # Number of rows to process at a time

def setup_database():
    """Check if table exists and prepare for data load."""
    try:
        with CONN.connect() as conn:
            # Check if table exists
            query = text(f"""
                SELECT COUNT(*) 
                FROM INFORMATION_SCHEMA.TABLES 
                WHERE TABLE_SCHEMA = :schema 
                AND TABLE_NAME = :table_name
            """)
            result = conn.execute(query, {'schema': SCHEMA, 'table_name': TABLE_NAME})
            table_exists = result.scalar() > 0
            
            if table_exists:
                print(f"Table {SCHEMA}.{TABLE_NAME} already exists. It will be truncated before loading new data.")
            else:
                print(f"Table {SCHEMA}.{TABLE_NAME} does not exist. It will be created automatically.")
                
        return True
        
    except Exception as e:
        print(f"Error checking database: {e}")
        return False

def load_data(csv_path):
    """Load data from CSV into the database."""
    try:
        # Check if file exists
        if not os.path.exists(csv_path):
            print(f"Error: File not found: {csv_path}")
            return False
            
        print(f"Loading data from: {csv_path}")
        
        # First, truncate the existing table if it exists
        with CONN.connect() as conn:
            # Start a transaction
            with conn.begin():
                # Truncate existing table if it exists
                conn.execute(text(f"""
                    IF OBJECT_ID(:schema_table, 'U') IS NOT NULL 
                    TRUNCATE TABLE {SCHEMA}.{TABLE_NAME}
                """), {'schema_table': f'{SCHEMA}.{TABLE_NAME}'})
        
        # Read and process CSV in chunks
        chunk_reader = pd.read_csv(csv_path, chunksize=CHUNK_SIZE, low_memory=False)
        total_rows = 0
        
        for i, chunk in enumerate(chunk_reader, 1):
            # Clean column names (remove spaces, special characters, etc.)
            chunk.columns = [str(col).strip().replace(' ', '_').replace('-', '_').lower() for col in chunk.columns]
            
            # Remove timestamp columns that are auto-generated by SQL Server
            timestamp_columns = []  # We'll handle etl_load_dt separately
            
            # Convert date columns to datetime
            for col in chunk.select_dtypes(include=['object']).columns:
                if 'date' in col.lower() or 'dt' in col.lower():
                    try:
                        if col == 'etl_load_dt':
                            # Parse datetime and remove timezone offset
                            chunk[col] = pd.to_datetime(chunk[col], errors='coerce').dt.tz_localize(None)
                        else:
                            chunk[col] = pd.to_datetime(chunk[col], errors='coerce')
                    except Exception as e:
                        print(f"Warning: Could not convert column '{col}' to datetime: {e}")
            
            # Drop any timestamp columns that should be excluded
            for col in timestamp_columns:
                if col in chunk.columns:
                    chunk = chunk.drop(columns=[col])
                    print(f"Excluded timestamp column: {col}")
            
            # Write chunk to database
            chunk.to_sql(
                name=TABLE_NAME,
                schema=SCHEMA,
                con=CONN,
                if_exists='append',  # Append to existing table
                index=False,
                chunksize=1000
            )
            
            total_rows += len(chunk)
            print(f"Processed {total_rows:,} rows...")
        
        print(f"Successfully loaded {total_rows:,} rows into {SCHEMA}.{TABLE_NAME}")
        return True
        
    except Exception as e:
        print(f"Error loading data: {e}")
        return False

def main():
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <path_to_csv>")
        sys.exit(1)
        
    csv_path = sys.argv[1]
    
    print("Starting data load process...")
    print(f"Target: SQL Server - {SCHEMA}.{TABLE_NAME}")
    
    try:
        if not setup_database():
            print("Error setting up database. Exiting.")
            return
            
        success = load_data(csv_path)
        
        if success:
            # Verify the data was loaded
            with CONN.connect() as conn:
                result = conn.execute(text(f"SELECT COUNT(*) FROM {SCHEMA}.{TABLE_NAME}")).scalar()
                print(f"Verification: Found {result:,} rows in {SCHEMA}.{TABLE_NAME}")
        
    except Exception as e:
        print(f"An error occurred: {e}")
    finally:
        print("Process completed.")

if __name__ == "__main__":
    main()
